version: "3"
 
services:
 
  nginx:
    image: nginx
    ports:
      - 99:80
      - 443:443
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
